name: Drupal

on: 
  push:
    branches: 
      - 'develop'
      - 'feature-*'
      - 'hotfix-*'
  pull_request:
    branches: 
      - 'develop'
jobs:
  build:
    runs-on: ubuntu-20.04

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    env:
      XDEBUG_MODE: coverage

    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring
        tools: composer
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_KEY }}
        config: ${{ secrets.PANTHEON_SSH_CONFIG }}
        known_hosts: ${{ secrets.PANTHEON_KNOWN_HOSTS }}     
    - name: Run deploy script
      env:
        PANTHEON_ENV: ${{ secrets.PANTHEON_ENV }}
        PANTHEON_REPO: ${{ secrets.PANTHEON_REPO }}
        PANTHEON_SITE_ID: ${{ secrets.PANTHEON_SITE_ID }}
        SECRET_TERMINUS_TOKEN: ${{ secrets.SECRET_TERMINUS_TOKEN }}
        GH_BUILD_NUMBER: ${{ github.run_number }}
        WORK_DIR: ${{ github.workspace }}
      run: bash .ci/deploy.sh
    - name: Run script
      run: |
        # npm install backstopjs
        echo "skipping tests"
